# Need super user permissions for Docker
sudo: required
services:
  # Use docker-cli
  - docker

before_install:
  - docker build -t philosocode/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true philosocode/docker-react npm run test -- --coverage